/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/common/AppHeader/AppHeader.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CellEditor: typeof import('./src/components/Lessons/common/CellEditor.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DevelopingStub: typeof import('./src/components/layouts/DevelopingStub.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LessonsLoadSelect: typeof import('./src/components/Lessons/common/LessonsLoadSelect.vue')['default']
    LessonsTable: typeof import('./src/components/Lessons/LessonsTable.vue')['default']
    LessonsTableHeader: typeof import('./src/components/Lessons/LessonsTableHeader.vue')['default']
    MainHeader: typeof import('./src/components/layouts/MainHeader.vue')['default']
    MainHeaderAccount: typeof import('./src/components/layouts/MainHeaderAccount.vue')['default']
    MainHeaderLink: typeof import('./src/components/layouts/MainHeaderLink.vue')['default']
    MainHeaderNav: typeof import('./src/components/layouts/MainHeaderNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SemesterSelect: typeof import('./src/components/Lessons/SemesterSelect.vue')['default']
    Stub: typeof import('./src/components/layouts/Stub.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
}
