name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: self-hosted

    env:
      TAG: "localhost:5050/ap-front-build:latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build --no-cache \ 
            --build-arg VITE_API=https://ap.mospolytech.ru/api/cabinet \
            --build-arg VITE_KD_ROOT=https://kd.mospolytech.ru/api/ \
            --build-arg VITE_API_KD=https://ap.mospolytech.ru/api/ \
            -t $TAG . 

      - name: Push Docker Image to Local Registry
        run: |
          docker push $TAG

      - name: Restart Services with Docker Compose
        working-directory: /opt/registry-apps/ap
        run: |
          docker-compose down
          docker-compose -d
